parameters:
    database_user: 'root'
    database_name: 'tictactoe'
    database_host: 'localhost'
    database_password: ~

routing:
    homepage:
        pattern: /
        controller: DefaultController
        action: indexAction
    auth:
        pattern: /auth
        controller: SecurityController
        action: authAction
    login:
        pattern: /login
        controller: SecurityController
        action: loginAction
    logout:
        pattern: /logout
        controller: SecurityController
        action: logoutAction
    registration:
        pattern: /registration
        controller: SecurityController
        action: registerAction
    click:
        pattern: /api/click
        controller: ApiController
        action: clickAction
